#!/usr/bin/env bash
# Re-take `stayhub-schema.sql` from the live StayHub database.
#
# Run this after a StayHub migration, so the lab database keeps matching the app it teaches.
# Two edits are applied on the way out, and both are needed:
#
#   1. `CREATE SCHEMA public` is dropped — a fresh database already has one, and pg_dump emits
#      the line anyway. Left in, the restore aborts with `schema "public" already exists`.
#   2. The extensions are prepended. `pg_dump -n public` filters them out because an extension
#      does not live in a schema, and without btree_gist the bookings EXCLUDE constraint cannot
#      be created at all.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/stayhub-schema.sql"

{
    echo "-- Generated by lab/dump-schema.sh from the live stayhub database. Do not hand-edit."
    echo "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
    echo "CREATE EXTENSION IF NOT EXISTS btree_gist;"
    echo
    docker exec stayhub-postgres pg_dump -U stayhub -d stayhub \
        --schema-only --no-owner --no-privileges -n public \
        | grep -v '^CREATE SCHEMA public;$'
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
