#!/usr/bin/env python3
"""Emit the lesson index for post 1, grouped by part, in reading order.

A hand-written index of 52 links drifts the first time a lesson is inserted or
retitled, and nothing checks it. This generates it from the manifest instead.

    projects/mysql_tutorial/gen_index.py            # print the HTML
    projects/mysql_tutorial/gen_index.py --check    # is post 1 in step?

`--check` is what stops the drift: it compares the block currently between the
INDEX START/END markers in post 1 against what the manifest says it should be.
"""

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import manifest  # noqa: E402

START = "<!-- INDEX START -- generated by gen_index.py, do not edit by hand -->"
END = "<!-- INDEX END -->"


def render() -> str:
    lines = [START]
    part = None
    for entry in manifest.POSTS:
        if entry["part"] != part:
            if part is not None:
                lines.append("</ul>")
            part = entry["part"]
            lines.append(f"<h3>{part}</h3>")
            lines.append("<ul>")
        # The post that holds the index links to itself; render it as plain text.
        if entry["slug"] == manifest.POSTS[0]["slug"]:
            lines.append(f"  <li>{entry['title']} — you are here</li>")
        else:
            lines.append(
                f'  <li><a href="/{manifest.CATEGORY["slug"]}/{entry["slug"]}">'
                f'{entry["title"]}</a></li>')
    lines.append("</ul>")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    expected = render()
    if not args.check:
        print(expected)
        return 0

    path = HERE / "posts" / manifest.POSTS[0]["file"]
    if not path.exists():
        print(f"{path.name} is not written yet — nothing to check.")
        return 0
    body = path.read_text(encoding="utf-8")
    found = re.search(re.escape(START) + r".*?" + re.escape(END), body, re.S)
    if not found:
        print(f"{path.name} has no INDEX START/END markers — the index is not generated.")
        return 1
    if found.group(0).strip() != expected.strip():
        print(f"{path.name}: the lesson index is out of step with the manifest.\n"
              "Re-run gen_index.py and paste the result between the markers.")
        return 1
    print(f"{path.name}: lesson index matches the manifest ({len(manifest.POSTS)} lessons).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
